version: '3'
services:

    db:
        image: mysql:5.7
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: your-password
            MYSQL_DATABASE: your-database
        restart: always

    redmine:
        image: redmine
        ports:
            - 3000:3000
        environment:
            REDMINE_DB_MYSQL: db
            REDMINE_DB_PASSWORD: your-password
        restart: always
